#pragma once

#include <cstddef>
#include <cstdint>
#include <string>

// Per-build compile-time string masking. The seeds are generated by Gradle,
// so releases do not share the same native string table or mask schedule.
#ifndef TSOB_KEY_A
#define TSOB_KEY_A 0x6A09E667F3BCC909ULL
#endif
#ifndef TSOB_KEY_B
#define TSOB_KEY_B 0xBB67AE8584CAA73BULL
#endif

constexpr std::uint64_t tso_mix(std::uint64_t value) {
    value ^= value >> 30;
    value *= 0xBF58476D1CE4E5B9ULL;
    value ^= value >> 27;
    value *= 0x94D049BB133111EBULL;
    value ^= value >> 31;
    return value;
}

template <std::size_t N>
constexpr std::uint64_t tso_literal_id(const char (&text)[N]) {
    std::uint64_t hash = 0xCBF29CE484222325ULL ^ static_cast<std::uint64_t>(N);
    for (std::size_t i = 0; i + 1 < N; ++i) {
        hash ^= static_cast<unsigned char>(text[i]);
        hash *= 0x100000001B3ULL;
        hash ^= hash >> 29U;
    }
    return tso_mix(hash ^ TSOB_KEY_A ^ tso_mix(TSOB_KEY_B));
}

constexpr unsigned char tso_mask(std::size_t index, std::uint64_t literal,
                                 std::uint64_t key_a, std::uint64_t key_b) {
    const std::uint64_t seed = tso_mix(key_a ^ tso_mix(key_b + literal * 0x9E3779B97F4A7C15ULL));
    const std::uint64_t stream = tso_mix(seed + (index + 1U) * 0xD6E8FEB86659FD93ULL);
    const unsigned shift = static_cast<unsigned>((index & 7U) * 8U);
    return static_cast<unsigned char>(((stream >> shift) ^ (stream >> 41U) ^ (key_b >> ((index & 7U) * 8U))) & 0xFFU);
}

template <std::size_t N, std::uint64_t Literal>
struct Enc {
    char buf[N];

    constexpr Enc(const char (&text)[N]) : buf{} {
        for (std::size_t i = 0; i < N; ++i) {
            buf[i] = static_cast<char>(
                    static_cast<unsigned char>(text[i]) ^ tso_mask(i, Literal, TSOB_KEY_A, TSOB_KEY_B));
        }
    }

    std::string get() const {
        std::string out(N > 0 ? N - 1 : 0, '\0');
        for (std::size_t i = 0; i + 1 < N; ++i) {
            out[i] = static_cast<char>(
                    static_cast<unsigned char>(buf[i]) ^ tso_mask(i, Literal, TSOB_KEY_A, TSOB_KEY_B));
        }
        return out;
    }
};

#define XS(literal) ([]() { constexpr Enc<sizeof(literal), tso_literal_id(literal)> value(literal); return value.get(); }())
